In [ ]:
!pip install pdfplumber pandas
!pip install camelot-py[cv] pandas numpy ghostscript
!pip install PyPDF2

Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 5.6 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 66.3 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 93.7 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 72.8 MB/s eta 0:00:00
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.13.0
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Collecting ghostscript
  Downloading ghostscript-0.8.1-py3-none-any.whl.metadata (4.4 kB)
Collecting camelot-py[cv]
  Downloading camelot_py-2.0.0-py3-none-any.whl.metadata (13 kB)
WARNING: camelot-py 2.0.0 does not provide the extra 'cv'
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.13/dist-packages (from camelot-py[cv]) (8.5.0)
Requirement already satisfied: openpyxl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from camelot-py[cv]) (3.1.5)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from camelot-py[cv]) (0.9.0)
Requirement already satisfied: opencv-python-headless>=4.7.0.68 in /usr/local/lib/python3.13/dist-packages (from camelot-py[cv]) (5.0.0.93)
Requirement already satisfied: pypdfium2>=4 in /usr/local/lib/python3.13/dist-packages (from camelot-py[cv]) (5.13.0)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.13/dist-packages (from camelot-py[cv]) (12.3.0)
Collecting playa-pdf>=0.8.1 (from camelot-py[cv])
  Downloading playa_pdf-1.1.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (27 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl>=3.1.0->camelot-py[cv]) (2.0.0)
Collecting mypy-extensions (from playa-pdf>=0.8.1->camelot-py[cv])
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading ghostscript-0.8.1-py3-none-any.whl (25 kB)
Downloading playa_pdf-1.1.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 52.1 MB/s eta 0:00:00
Downloading camelot_py-2.0.0-py3-none-any.whl (113 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.2/113.2 kB 9.8 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: ghostscript, mypy-extensions, playa-pdf, camelot-py
Successfully installed camelot-py-2.0.0 ghostscript-0.8.1 mypy-extensions-1.1.0 playa-pdf-1.1.0
Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.8 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [ ]:
#@title Helper Functions

def clean(text):
    if text is None:
        return ""
    return re.sub(r"\s+", " ", str(text)).strip()

def normalize_row(cells):
    """
    Pads / trims row to exactly 6 columns
    """
    cells = [clean(c) for c in cells]
    if len(cells) < len(COLUMNS):
        cells += [""] * (len(COLUMNS) - len(cells))
    return cells[:len(COLUMNS)]

def page_chunks(total, size):
    for start in range(1, total + 1, size):
        end = min(start + size - 1, total)
        yield f"{start}-{end}"

def main():
    # Count pages
    with pdfplumber.open(PDF_PATH) as pdf:
        total_pages = len(pdf.pages)

    all_rows = []

    for page_range in page_chunks(total_pages, CHUNK_SIZE):
        print(f"Processing pages {page_range}")
        tables = camelot.read_pdf(
            PDF_PATH,
            pages=page_range,
            flavor="lattice",
            strip_text="\n"
        )

        for table in tables:
            df = table.df

            for _, row in df.iterrows():
                cells = normalize_row(row.tolist())

                # Skip ONLY true header rows
                joined = " ".join(cells).lower()
                if "sno" in joined and "rank" in joined and "institute" in joined:
                    continue

                all_rows.append(dict(zip(COLUMNS, cells)))

    final_df = pd.DataFrame(all_rows, columns=COLUMNS)
    display(final_df)
    final_df.to_csv(OUTPUT_CSV, index=False)

    print(f"\n✅ Extracted {len(final_df)} rows to {OUTPUT_CSV}")

# Extraction

In [ ]:
#@title Extracting from PDF as-is R1
import camelot
import pandas as pd
import re
import pdfplumber

PDF_PATH = "r1_neet_pg_2025.pdf"
OUTPUT_CSV = "r1_neet_pg_2025.csv"
CHUNK_SIZE = 40

COLUMNS = [
    "sno","R1_Rank","R1_Allot_Quota","R1_Institute","R1_Course","R1_Allot_Cat","R1_Cand_Cat","R1_Remarks"
]

if __name__ == "__main__":
    main()

In [ ]:
#@title Extracting from PDF as-is R2
import camelot
import pandas as pd
import re
import pdfplumber

PDF_PATH = "r2_neet_pg_2025.pdf"
OUTPUT_CSV = "r2_neet_pg_2025.csv"
CHUNK_SIZE = 40

COLUMNS = [
    "sno","R1_Rank","R1_Allot_Quota","R1_Institute","R1_Course","R1_Remarks",
                    "R2_Allot_Quota","R2_Institute", "R2_Course", "R2_Allot_Cat", "R2_Cand_Cat", "R2_Opt_No","R2_Remarks"
]

if __name__ == "__main__":
    main()

Processing pages 1-40
Processing pages 41-80
Processing pages 81-120
Processing pages 121-160
Processing pages 161-200
Processing pages 201-240
Processing pages 241-280
Processing pages 281-320
Processing pages 321-360
Processing pages 361-400
Processing pages 401-440
Processing pages 441-480
Processing pages 481-520
Processing pages 521-560
Processing pages 561-600
Processing pages 601-640
Processing pages 641-680
Processing pages 681-720
Processing pages 721-760
Processing pages 761-800
Processing pages 801-840
Processing pages 841-880
Processing pages 881-920
Processing pages 921-960
Processing pages 961-1000
Processing pages 1001-1040
Processing pages 1041-1080
Processing pages 1081-1120
Processing pages 1121-1160
Processing pages 1161-1200
Processing pages 1201-1240
Processing pages 1241-1280
Processing pages 1281-1320
Processing pages 1321-1360
Processing pages 1361-1400
Processing pages 1401-1440
Processing pages 1441-1480
Processing pages 1481-1520
Processing pages 1521-1560
Processing pages 1561-1600
Processing pages 1601-1640
Processing pages 1641-1680
Processing pages 1681-1720
Processing pages 1721-1760
Processing pages 1761-1800
Processing pages 1801-1840
Processing pages 1841-1880
Processing pages 1881-1920
Processing pages 1921-1960
Processing pages 1961-2000
Processing pages 2001-2040
Processing pages 2041-2080
Processing pages 2081-2120
Processing pages 2121-2160
Processing pages 2161-2200
Processing pages 2201-2240
Processing pages 2241-2280
Processing pages 2281-2320
Processing pages 2321-2360
Processing pages 2361-2400
Processing pages 2401-2440
Processing pages 2441-2480
Processing pages 2481-2520
Processing pages 2521-2560
Processing pages 2561-2600
Processing pages 2601-2640
Processing pages 2641-2680
Processing pages 2681-2720
Processing pages 2721-2760
Processing pages 2761-2800
Processing pages 2801-2840
Processing pages 2841-2844

,sno,R1_Rank,R1_Allot_Quota,R1_Institute,R1_Course,R1_Remarks,R2_Allot_Quota,R2_Institute,R2_Course,R2_Allot_Cat,R2_Cand_Cat,R2_Opt_No,R2_Remarks
0,Quota Abbrevation,,,,,,,,,,,,
1,Abbrevation,Description,,,,,,,,,,,
2,AM,Aligarh Muslim University,,,,,,,,,,,
3,AI,All India,,,,,,,,,,,
4,AF,Armed Forces Medical,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35046,138558,Non-ResidentIndian,Sri Ramachandra MedicalCollege and ResearchIns...,M.S.(ORTHOPAEDICS),Reported,-,-,-,-,-,-,Did not optforUpgradation.,
35047,138577,All India,GOVT MEDICALCOLLEGE KOTTAYAM,M.D. (GENERALMEDICINE),NotReported,-,-,-,-,-,-,Not Allotted.,
35048,138605,-,-,-,-,All India,"Gulbarga Institute Of MedicalSciences, Kalabur...",M.D.(PHYSIOLOGY),OBC,OBC,103,Fresh Allottedin 2nd Round,
35049,138607,DNB Quota,"S.K.Hospital,",(NBEMS-DIPLOMA)OPHTHALMOLOGY,Reported,-,-,-,-,-,-,NoUpgradation,
35050,138628,-,-,-,-,Self-FinancedMerit Seat,SHRI. B. M. PATIL MEDICALCOLLEGE HOSPITAL ANDR...,M.D.(PHARMACOLOGY),Open,OBC,478,Fresh Allottedin 2nd Round,

✅ Extracted 35051 rows to r2_neet_pg_2025.csv

In [ ]:
#@title Extracting from PDF as-is R3
import camelot
import pandas as pd
import re
import pdfplumber

PDF_PATH = "r3_neet_pg_2025.pdf"
OUTPUT_CSV = "r3_neet_pg_2025.csv"
CHUNK_SIZE = 40

COLUMNS = [
"sno","R1_Rank","R1_Allot_Quota","R1_Institute","R1_Course","R1_Remarks",
                "R2_Allot_Quota","R2_Institute", "R2_CourseID", "R2_Remarks",
                "R3_Allot_Quota","R3_Institute", "R3_Course", "R3_Allot_Cat", "R3_Cand_Cat", "R3_Opt_No","R3_Remarks"
]

if __name__ == "__main__":
    main()

Processing pages 1-40
Processing pages 41-80
Processing pages 81-120
Processing pages 121-160
Processing pages 161-200
Processing pages 201-240
Processing pages 241-280
Processing pages 281-320
Processing pages 321-360
Processing pages 361-400
Processing pages 401-440
Processing pages 441-480
Processing pages 481-520
Processing pages 521-560
Processing pages 561-600
Processing pages 601-640
Processing pages 641-680
Processing pages 681-720
Processing pages 721-760
Processing pages 761-800
Processing pages 801-840
Processing pages 841-880
Processing pages 881-920
Processing pages 921-960
Processing pages 961-1000
Processing pages 1001-1040
Processing pages 1041-1080
Processing pages 1081-1120
Processing pages 1121-1160
Processing pages 1161-1200
Processing pages 1201-1240
Processing pages 1241-1280
Processing pages 1281-1320
Processing pages 1321-1360
Processing pages 1361-1400
Processing pages 1401-1440
Processing pages 1441-1480
Processing pages 1481-1520
Processing pages 1521-1555

,sno,R1_Rank,R1_Allot_Quota,R1_Institute,R1_Course,R1_Remarks,R2_Allot_Quota,R2_Institute,R2_CourseID,R2_Remarks,R3_Allot_Quota,R3_Institute,R3_Course,R3_Allot_Cat,R3_Cand_Cat,R3_Opt_No,R3_Remarks
0,Quota Abbrevation,,,,,,,,,,,,,,,,
1,Abbrevation,Description,,,,,,,,,,,,,,,
2,AM,Aligarh Muslim University,,,,,,,,,,,,,,,
3,AI,All India,,,,,,,,,,,,,,,
4,AF,Armed Forces Medical,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41819,229870,-,-,-,-,-,-,-,-,All India,EMPLOYEES STATE INSURANCE CORPORATIONMEDICAL C...,M.D. IN TRANSFUSIONMEDICINE/ IMMUNO-HAEMATOLOG...,OBCPwD,OBCPwD,19,Fresh Allottedin 3nd Round,
41820,229954,-,-,-,-,-,-,-,-,All India,Pandit Bhagwat Dayal Sharma Post Graduate Inst...,M.S. (ORTHOPAEDICS),OBCPwD,OBCPwD,38,Fresh Allottedin 3nd Round,
41821,230056,-,-,-,-,-,-,-,-,Self-FinancedMeritSeat,"Symbiosis Medical College for Women,Lavale, Mu...",M.D. (BIOCHEMISTRY),Open,SC,111,Fresh Allottedin 3nd Round,
41822,230074,-,-,-,-,-,-,-,-,All India,"Gvernment Medical College,Haldwani,Government ...",M.D. (BIOCHEMISTRY),ST,ST,128,Fresh Allottedin 3nd Round,
41823,230087,-,-,-,-,-,-,-,-,Self-FinancedMeritSeat,"A.C.S. Medical College and Hospital,A.C.S. Med...",M.D. (PHYSIOLOGY),Open,OBC,1227,Fresh Allottedin 3nd Round,

✅ Extracted 41824 rows to r3_neet_pg_2025.csv

# Clean up

In [ ]:
import pandas as pd
df_r1 = pd.read_csv("r1_neet_pg_2025.csv")
df_r2 = pd.read_csv("r2_neet_pg_2025.csv")
df_r3 = pd.read_csv("r3_neet_pg_2025.csv")

In [ ]:
#combine rank and group to create unique ID
df_r1 = df_r1.rename(columns={"R1_Rank": "Rank", "R1_Course":"Course" ,"R1_Institute": "Institute",
                              "R1_Allot_Quota":"Allot_Quota","R1_Allot_Cat": "Allot_Cat" ,"R1_Cand_Cat":"Cand_Cat",
                              "R1_Remarks": "Remarks"})
df_r1 = df_r1.drop(columns=["sno"])
df_r1["Round"] = 1
df_r1

,Rank,Allot_Quota,Institute,Course,Allot_Cat,Cand_Cat,Remarks,uid,Round
0,1,All India,"PGIMER, DR. RML Hospital, Cannaught Place, New...",M.D. (GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_1,1
1,2,All India,"Government Medical College Kozhikode,Governmen...",M.D. (GENERALMEDICINE),Open,OBC,Allotted,m.d.(generalmedicine)_2,1
2,3,All India,"PGIMER, DR. RML Hospital, Cannaught Place, New...",M.D. (GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_3,1
3,4,All India,"Vardhman Mahavir Medical College, , New Delhi,...",M.D. (RADIO-DIAGNOSIS),Open,General,Allotted,m.d.(radio-diagnosis)_4,1
4,5,All India,"PGIMER, DR. RML Hospital, Cannaught Place, New...",M.D. (GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_5,1
...,...,...,...,...,...,...,...,...,...
26884,138383,Self-Financed MeritSeat/(Paid SeatQuota),"SRI DEVARAJ URS MEDICAL COLLEGE, TAMAKA,Tamaka...",M.D. (PREVENTIVE andSOCIAL MEDICINE)/COMMUNITY...,Open,OBC,Allotted,m.d.(preventiveandsocialmedicine)/communitymed...,1
26885,138397,Self-Financed MeritSeat/(Paid SeatQuota),SRM MEDICAL COLLEGE HOSPITAL AND RESEARCH CENT...,M.D. (FORENSICMEDICINE),Open,OBC,Allotted,m.d.(forensicmedicine)_138397,1
26886,138558,Non-Resident Indian,Sri Ramachandra Medical College and Research I...,M.S. (ORTHOPAEDICS),Open,OBC,Allotted( NRIPriority : 2 ),m.s.(orthopaedics)_138558,1
26887,138577,All India,"GOVT MEDICAL COLLEGE KOTTAYAM,GOVT MEDICAL COL...",M.D. (GENERALMEDICINE),OBCPwD,OBC PwD,Allotted,m.d.(generalmedicine)_138577,1
26888,138607,DNB Quota,"S.K.Hospital, ,SUPERINTENDENT RNO 36 GOVT SK H...",(NBEMS-DIPLOMA)OPHTHALMOLOGY,ST,ST,Allotted,(nbems-diploma)ophthalmology_138607,1

In [ ]:
df_r2 = df_r2.rename(columns={"R1_Rank": "Rank", "R2_Course":"Course" ,"R2_Institute": "Institute",
                              "R2_Allot_Quota":"Allot_Quota","R2_Allot_Cat": "Allot_Cat" ,"R2_Cand_Cat":"Cand_Cat",
                             "R2_Remarks": "Remarks"})
df_r2 = df_r2.drop(columns=["R1_Institute", "R1_Course", "R1_Remarks", "R1_Allot_Quota","R2_Opt_No" ])
df_r2 = df_r2[df_r2.Rank!= "-"]
df_r2["Round"] = 2
df_r2

,Rank,Allot_Quota,Institute,Course,Allot_Cat,Cand_Cat,Remarks,uid,Round
0,1,-,-,-,-,-,Did not optforUpgradation.,-_1,2
1,2,-,-,-,-,-,Did not optforUpgradation.,-_2,2
2,3,-,-,-,-,-,Did not fill upfresh choices.,-_3,2
3,4,-,-,-,-,-,Did not optforUpgradation.,-_4,2
4,5,-,-,-,-,-,Did not fill upfresh choices.,-_5,2
...,...,...,...,...,...,...,...,...,...
35018,138558,-,-,-,-,-,Did not optforUpgradation.,-_138558,2
35019,138577,-,-,-,-,-,Not Allotted.,-_138577,2
35020,138605,All India,"Gulbarga Institute Of MedicalSciences, Kalabur...",M.D.(PHYSIOLOGY),OBC,OBC,Fresh Allottedin 2nd Round,m.d.(physiology)_138605,2
35021,138607,-,-,-,-,-,NoUpgradation,-_138607,2
35022,138628,Self-FinancedMerit Seat,SHRI. B. M. PATIL MEDICALCOLLEGE HOSPITAL ANDR...,M.D.(PHARMACOLOGY),Open,OBC,Fresh Allottedin 2nd Round,m.d.(pharmacology)_138628,2

In [ ]:
df_r3 = df_r3.rename(columns={"R1_Rank": "Rank", "R3_Course": "Course","R3_Institute": "Institute",
                              "R3_Allot_Quota":"Allot_Quota","R3_Allot_Cat": "Allot_Cat" ,"R3_Cand_Cat":"Cand_Cat",
                               "R3_Remarks": "Remarks"})
df_r3 = df_r3.drop(columns=["R1_Institute", "R2_Institute", "R1_Allot_Quota",	"R2_Allot_Quota",
                            "R1_Course", "R2_CourseID", "R1_Remarks", "R2_Remarks" ,
                            "R3_Opt_No"
                            ])
df_r3 = df_r3[df_r3.Rank!= "-"]
df_r3["Round"] = 3
df_r3

,Rank,Allot_Quota,Institute,Course,Allot_Cat,Cand_Cat,Remarks,uid,Round
0,1,-,-,-,-,-,Did not opt forUpgradation.,-_1,3
1,2,-,-,-,-,-,Did not opt forUpgradation.,-_2,3
2,3,-,-,-,-,-,Did not fill upfresh choices.,-_3,3
3,4,-,-,-,-,-,Did not opt forUpgradation.,-_4,3
4,5,-,-,-,-,-,Did not fill upfresh choices.,-_5,3
...,...,...,...,...,...,...,...,...,...
41689,229870,All India,EMPLOYEES STATE INSURANCE CORPORATIONMEDICAL C...,M.D. IN TRANSFUSIONMEDICINE/ IMMUNO-HAEMATOLOG...,OBCPwD,OBCPwD,Fresh Allottedin 3nd Round,m.d.intransfusionmedicine/immuno-haematologyan...,3
41690,229954,All India,Pandit Bhagwat Dayal Sharma Post Graduate Inst...,M.S. (ORTHOPAEDICS),OBCPwD,OBCPwD,Fresh Allottedin 3nd Round,m.s.(orthopaedics)_229954,3
41691,230056,Self-FinancedMeritSeat,"Symbiosis Medical College for Women,Lavale, Mu...",M.D. (BIOCHEMISTRY),Open,SC,Fresh Allottedin 3nd Round,m.d.(biochemistry)_230056,3
41692,230074,All India,"Gvernment Medical College,Haldwani,Government ...",M.D. (BIOCHEMISTRY),ST,ST,Fresh Allottedin 3nd Round,m.d.(biochemistry)_230074,3
41693,230087,Self-FinancedMeritSeat,"A.C.S. Medical College and Hospital,A.C.S. Med...",M.D. (PHYSIOLOGY),Open,OBC,Fresh Allottedin 3nd Round,m.d.(physiology)_230087,3

In [ ]:
df_r1.shape, df_r2.shape, df_r3.shape

((11348, 9), (35023, 9), (21874, 9))

In [ ]:
#@title Standardise names of institutes, groups, and courses across the three rounds

#concatenate all the dfs
df = pd.concat([df_r1, df_r2, df_r3], ignore_index=True)

#from quick manual skim of the data it seems that non-uniform spacing throughout
#the names is causing same insts/courses to show up as unique entries.
#This will cause issues when we want to group data by inst/course

print("Unique values before removing spaces")

print("Institute names: ", len(df["Institute"].unique()))
print("Alloted Quota:", len(df["Allot_Quota"].unique()))
print("Course names: ",len(df["Course"].unique()))

df["Institute"] = df["Institute"].str.replace(' ', '')
df["Allot_Quota"] = df["Allot_Quota"].str.replace(' ', '')
df["Course"] = df["Course"].str.replace(' ', '')

print("\nUnique values after removing spaces")

print("Institute names: ",len(df["Institute"].unique()))
print("Course names: ", len(df["Course"].unique()))
print("Alloted Quota:", len(df["Allot_Quota"].unique()))

# #now uniformly add spaces to institute names/addresses after each comma in the string
df["Institute"] = df["Institute"].str.replace(',', ', ')
df.head(5)

Unique values before removing spaces
Institute names:  5118
Alloted Quota: 25
Course names:  192

Unique values after removing spaces
Institute names:  1893
Course names:  102
Alloted Quota: 14

,Rank,Allot_Quota,Institute,Course,Allot_Cat,Cand_Cat,Remarks,uid,Round
0,1,AllIndia,"PGIMER, DR.RMLHospital, CannaughtPlace, NewDel...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_1,1
1,2,AllIndia,"GovernmentMedicalCollegeKozhikode, GovernmentM...",M.D.(GENERALMEDICINE),Open,OBC,Allotted,m.d.(generalmedicine)_2,1
2,3,AllIndia,"PGIMER, DR.RMLHospital, CannaughtPlace, NewDel...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_3,1
3,4,AllIndia,"VardhmanMahavirMedicalCollege, , NewDelhi, Var...",M.D.(RADIO-DIAGNOSIS),Open,General,Allotted,m.d.(radio-diagnosis)_4,1
4,5,AllIndia,"PGIMER, DR.RMLHospital, CannaughtPlace, NewDel...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_5,1

In [ ]:
df = pd.read_csv('neet_pg_2025_results_long_format_v2.tsv', sep='\t')

In [ ]:
#@title Identifying final round of allotment for each candidate

import numpy as np
# finds the latest round of all rounds the candidate participated in
latest = (
    df
    .groupby("Rank", as_index=False)["Round"]
    .max()
    .rename(columns={"Round": "latest_round"})
)

df = df.merge(latest, on="Rank", how="left")

# If latest round value for that candidate matches the round in that row, assign final assignment status to that row
df["Round_assignment_status"] = np.where(
   (df["Round"] == df["latest_round"]),
    "Final assignment",
    ""
)
df=df.drop(columns=["latest_round"])
df.to_csv("neet_pg_2025_results_long_format_v3.tsv", sep="\t")
df.head(20)

,Rank,Allot_Quota,Institute,Course,Allot_Cat,Cand_Cat,Remarks,uid,Round_Assignment_Status,Round,Lat,Lon,Area,State,Pincode,Round_assignment_status
0,1,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_1,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,Final assignment
1,2,AllIndia,"Government Medical College Kozhikode, Governme...",M.D.(GENERALMEDICINE),Open,OBC,Allotted,m.d.(generalmedicine)_2,Final assignment,1,11.272258,75.837230,Kozhikode,Keralam,673008,Final assignment
2,3,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_3,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,Final assignment
3,4,AllIndia,"Vardhman Mahavir Medical College, New Delhi, V...",M.D.(RADIO-DIAGNOSIS),Open,General,Allotted,m.d.(radio-diagnosis)_4,Final assignment,1,28.568976,77.203087,New Delhi,Delhi,110029,Final assignment
4,5,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_5,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,Final assignment
5,6,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_6,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,
6,6,AllIndia,"Maulana Azad Medical College, Maulana Azad Med...",M.D.(RADIO-DIAGNOSIS),Open,General,Fresh Allottedin 3nd Round,m.d.(radio-diagnosis)_6,Final assignment,3,28.635740,77.240071,New Delhi,Delhi,110002,Final assignment
7,7,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_7,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,Final assignment
8,8,AllIndia,Bangalore Medical Collegeand Research Institut...,M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_8,Final assignment,1,12.959414,77.574725,Bengaluru,Karnataka,560002,Final assignment
9,9,AllIndia,"MADRASMEDICALCOLLEGE, EVRPERIYARSALAI, CHENNAI...",M.D.(GENERALMEDICINE),Open,OBC,Allotted,m.d.(generalmedicine)_9,Final assignment,1,13.079819,80.272297,Chennai,Tamil Nadu,600003,Final assignment
10,10,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,OBC,Allotted,m.d.(generalmedicine)_10,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,
11,10,DNBQuota,"Metro Heart Institutewith Multispecialty, SECT...",(NBEMS)GENERALMEDICINE,Open,OBC,Fresh Allottedin 3nd Round,(nbems)generalmedicine_10,Final assignment,3,28.406241,77.318060,Faridabad,Haryana,121002,Final assignment
12,11,AllIndia,"Vardhman Mahavir Medical College, New Delhi, V...",M.D.(RADIO-DIAGNOSIS),Open,General,Allotted,m.d.(radio-diagnosis)_11,Final assignment,1,28.568976,77.203087,New Delhi,Delhi,110029,Final assignment
13,12,AllIndia,"MADRASMEDICALCOLLEGE, EVRPERIYARSALAI, CHENNAI...",M.D.(Obst.andGynae)/MS(ObstetricsandGynaecology),Open,General,Allotted,m.d.(obst.andgynae)/ms(obstetricsandgynaecolog...,Final assignment,1,13.079819,80.272297,Chennai,Tamil Nadu,600003,Final assignment
14,13,AllIndia,"Governmentmedicalcollegepatiala., Governmentme...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_13,NaN,1,30.328063,76.385128,Patiala,Punjab,147001,
15,13,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Fresh Allottedin 2nd Round,m.d.(generalmedicine)_13,Final assignment,2,28.625442,77.198942,New Delhi,Delhi,110001,Final assignment
16,14,AllIndia,"Vardhman Mahavir Medical College, New Delhi, V...",M.D.(Obst.andGynae)/MS(ObstetricsandGynaecology),Open,General,Allotted,m.d.(obst.andgynae)/ms(obstetricsandgynaecolog...,NaN,1,28.568976,77.203087,New Delhi,Delhi,110029,
17,14,AllIndia,"Vardhman Mahavir Medical College, New Delhi, V...",M.D.(Obst.andGynae)/MS(ObstetricsandGynaecology),Open,General,Fresh Allottedin 2nd Round,m.d.(obst.andgynae)/ms(obstetricsandgynaecolog...,Final assignment,2,28.568976,77.203087,New Delhi,Delhi,110029,Final assignment
18,15,AllIndia,"PGIMER, DR.RMLHospital, Cannaught Place, New D...",M.D.(GENERALMEDICINE),Open,General,Allotted,m.d.(generalmedicine)_15,Final assignment,1,28.625442,77.198942,New Delhi,Delhi,110001,Final assignment
19,16,AllIndia,"NIZAMSINSTITUTEOFMEDICALSCIENCES, NIZAMSINSTIT...",M.D.(GENERALMEDICINE),Open,EWS,Allotted,m.d.(generalmedicine)_16,Final assignment,1,17.426797,78.452480,Hyderabad,Telangana,500082,Final assignment

# Break workflow for manual cleanup on sheets

Bulk clean ups
1. Looking at blanks in each column and checking if any blank entries are due to unseparated adjacent column entries
2. Correcting spaces in individual columns to resolve unique entries
3. Using regex for introducing spaces before capitalised words - eg insititute names, address pieces, etc

Point clean ups: Addresses & Pincodes
1. Pincode from 70027 to 700027 for command hospital kolkata
2. Fixing , and pincode in: Kauvery Hospital Medical Services Pvt Ltd, vijay@kauveryhealthcare.com, No35, Shanthinagar, Oppositeto CSIchurch, **Hosur635109, Tamil Nadu,**
3. RAINBOWINSTITIUTEOFMEDICALSCIENCES(RIMS), Maharashtra, Beside Hotelneelam Opp Empire Mall Badnera Road Amravati Maharshtra444605, Maharashtra, 44605
4. Autonomous State Medical College Society, Etah, Uttar Pradesh., 112 Nagla Padihar, Sirao Mahrara Linkroad Sakeet, Etah Uttar Pradesh207001 Etah, Uttar Pradesh,
5. Diphu Medical College&Hospital, Thana Road, Diphu, Assam782462
6. ESICModeland Superspeciality Hospital, Asramam, Kollam, Kerala-69100, Asramam, Kollam, Kerala
7. Government Hospital, Rajasthan, Near Tilak Nagar Bus Stand, Barmer, Rajasthan-34400101
8. Grecian Super Speciality Hospital, (Aunitof R.G.SHealthcare Pvt.Ltd), Sector-69, Opp.Village Kumbra, S.A.SNagar, Mohali, Punjab-60062, Grecian Super Sepeciality Hospital Sec-69 Mohali Punjab
9. Government MEdical College, Ramagundam, Government Medical College Ramagundam92, 95, 96 Malkapur Village Ramagundam Mandal Pedapalli

All of the above steps can optionally be done in python as well.

## Additional columns
1. Extract pincodes using regex + sheets from institute addresses
2. Adding city name, state name, latitude and longitude using a geocoder -- added using sheets + appscript setup.
3. For institues where pincodes are not provided in the PDFs, use the geoding to get pincodes